apiVersion: anthos.cloud.google.com/v1alpha1
kind: ConfigManagementBinding
metadata:
  name: config-management-binding
  namespace: anthos-system
spec:
  configs:
  - configRef:
      name: config-management-spec-1
      namespace: anthos-system
    placement:
      clusters:
      - membership: "gke-cluster-1"
